### ISSUE TITLE
1주차: 3장까지(루씬의 기본 동작과 구조 및 인덱스 설계)

### ISSUE THREAD

**Issue by jdalma** [jdalma/elasticsearch-bible#1]
- `분산 처리나 고가용성, 수평적 확장성 등 엔터프라이즈 영역에 필요한 주요 기능을 제공하고 있다` 고 하는데 우리도 고가용성, 수평적 확장성이 사용되고 있는지? 예를 들어, 노드가 자동적으로 늘어나거나 줄어드는지? 페일오버와 페일백이 되는지?
- 역색인
- 주 샤드와 복제 샤드가 존재하는데 30p 설명에서 `원본 역할`이 있다고 하는데 명확히 어떤 역할이 있는건지?
- 문서를 삭제할 때도 version이 오름, 34p 세그먼트 내용에서 삭제 플래그만 표시해두는 것을 보니 바로 삭제하지 않는 것 같다. 관련해서 업데이트가 일어나도 삭제 플래그로 표시하고 새 세그먼트를 생성한다.
- 데이터 팀에서 일반적으로 말하는 인덱스는 엘라스틱서치 인덱스인지? 구분해서 얘기하는지?
- 데이터 노드만 세그먼트를 관리하는 것인가?
- ES는 메이저 버전이 하나 차이나는 인덱스만 읽어들일 수 있다. 메이저 버전이 둘 이상 차이나는 ES에서 생성한 인덱스는 신규 ES에서 읽어 들일 수 없다. 그럼 우리는?
- 역색인이 없기 때문에 일반적인 검색 대상이 되지 않는다.

**Comment by ShinyoungAshleyChoi** [comment]
> * `분산 처리나 고가용성, 수평적 확장성 등 엔터프라이즈 영역에 필요한 주요 기능을 제공하고 있다` 고 하는데 우리도 고가용성, 수평적 확장성이 사용되고 있는지? 예를 들어, 노드가 자동적으로 늘어나거나 줄어드는지? 페일오버와 페일백이 되는지?
- 책에는 수평적 확장성이 제공된다고 나와 있어 마치 손쉽게 노드를 늘리거나 줄일 수 있을 것으로 보이나 실제로 노드를 증가시키는 경우 샤드를 골고루 분배하기 위해서는 리인덱스를 해주어야 함. 즉 노드의 개수는 자동적으로 늘어나거나 줄어들지 않으며 리인덱스에 많은 시간이 소요되므로 노드를 늘리거나 줄이는 것은 제한적으로만 운영될 수 있음

- 다수의 노드를 사용하여 고가용성을 보장 받음

> * 역색인
-

> * 주 샤드와 복제 샤드가 존재하는데 30p 설명에서 `원본 역할`이 있다고 하는데 명확히 어떤 역할이 있는건지?
-

> * 문서를 삭제할 때도 version이 오름, 34p 세그먼트 내용에서 삭제 플래그만 표시해두는 것을 보니 바로 삭제하지 않는 것 같다. 관련해서 업데이트가 일어나도 삭제 플래그로 표시하고 새 세그먼트를 생성한다.
- 문서를 삭제하는 경우 merging(https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-merge.html) 하기 전까지 실제로 문서가 삭제되지는 않는다. 많은 nosql 데이터베이스들이 디테일한 작동 방식은 다를지라도 이와 비슷하게 작동하는 것 같다.

> * 데이터 팀에서 일반적으로 말하는 인덱스는 엘라스틱서치 인덱스인지? 구분해서 얘기하는지?
- 보통 문서묶음을 칭하는 인덱스는 "인덱스"라고 칭함, 인덱스에 문서를 insert하는 행위는 "인덱싱"이라고 칭함

> * 데이터 노드만 세그먼트를 관리하는 것인가?
-

**Comment by ShinyoungAshleyChoi** [comment]
> * ES에서 검색할 때 GET/POST 상관 없이 Query를 Body에 담아서 검색할 수 있는데 두 Method 중에서 어떠한 걸 사용하는 것이 옳다고 생각하는지?

- 책에도 나와 있듯이 명확한 무엇을 사용해야 맞는것이라는 명확한 기준이 없다. 다만 개인적인 생각으로는 RFC 프로토콜 상에서도 이를 제한하고 있지 않으며 많은 사용자가 엘라스틱의 가이드대로 GET 메서드를 사용하고 있으므로 관례상 GET을 사용하는 것이 개발자 간의 오해를 줄일 수 있으며 적절할 것 같다.

**Comment by jdalma** [comment]
> 책에는 수평적 확장성이 제공된다고 나와 있어 마치 손쉽게 노드를 늘리거나 줄일 수 있을 것으로 보이나 실제로 노드를 증가시키는 경우 샤드를 골고루 분배하기 위해서는 리인덱스를 해주어야 함. 즉 노드의 개수는 자동적으로 늘어나거나 줄어들지 않으며 문서의 용량이 큰 경우 리인덱스에 많은 시간이 소요되므로 노드를 늘리거나 줄이는 것은 제한적으로만 운영될 수 있음

수평적 확장에 대한 단점이 이해되었음
추가로 저희는 국가별로 인덱스를 구분하고 있는데 국가별 인덱스 마다 샤드 개수가 다 다름. 특허 데이터가 쌓일수록 샤드 크기는 커져가는데 저희도 리인덱스를 통해 샤드를 여러 노드에 재배치한 경우가 있는지?

> 보통 문서묶음을 칭하는 인덱스는 "인덱스"라고 칭함, 인덱스에 문서를 insert하는 행위는 "인덱싱"이라고 칭함

문서묶음은 세그먼트를 의미하고 인덱스는 엘라스틱서치 인덱스를 의미하는 것인지 궁금함

**Comment by ShinyoungAshleyChoi** [comment]
> * 데이터 노드만 세그먼트를 관리하는 것인가?
- 문서가 저장되는 노드가 데이터 노드이므로 세그먼트 관리 역시 데이터 노드의 역할 일 듯

**Comment by hasuikhs** [comment]
- ES 7.0.X 이전에는 document 상위 개념으로 mapping type이 존재했었는데 왜 삭제되었나?

**Comment by ShinyoungAshleyChoi** [comment]
> * ES 7.0.X 이전에는 document 상위 개념으로 mapping type이 존재했었는데 왜 삭제되었나?
처음에는 "인덱스"가 SQL 데이터베이스의 "데이터베이스"와 유사하고 "유형"이 "테이블"과 동일하다고 설명했습니다.

이는 잘못된 가정으로 이어지는 잘못된 비유였습니다. SQL 데이터베이스에서 테이블은 서로 독립적입니다. 한 테이블의 열은 다른 테이블의 동일한 이름을 가진 열과 관련이 없습니다. 매핑 유형의 필드에는 해당되지 않습니다.

Elasticsearch 인덱스에서는 서로 다른 매핑 유형에서 동일한 이름을 갖는 필드가 내부적으로 동일한 Lucene 필드로 지원됩니다. 즉, 위의 예를 사용하면 유형 user_name의 필드는 유형의 필드 user와 정확히 동일한 필드에 저장되며 두 필드는 두 유형 모두에서 동일한 매핑(정의)을 가져야 합니다.user_nametweetuser_name

예를 들어 동일한 인덱스에서 한 유형의 필드와 다른 유형의 필드가 deleted되기를 원할 때 이로 인해 좌절감을 느낄 수 있습니다 .dateboolean

게다가 동일한 인덱스에 공통 필드가 거의 없거나 전혀 없는 여러 엔터티를 저장하면 데이터가 희박해지고 문서를 효율적으로 압축하는 Lucene의 기능이 방해를 받습니다.

이러한 이유로 우리는 Elasticsearch에서 매핑 유형 개념을 제거하기로 결정했습니다.
(https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html)

**Comment by ShinyoungAshleyChoi** [comment]
> * 성능에 문제가 있을 수 있는 nested Type을 굳이 사용하는 이유?
- 한 문서 내에서 1 대 다 관계가 있는 경우 사용할 수 있다.
- {
  "title": "The Great Gatsby",
  "publication_year": 1925,
  "authors": [
    {
      "name": "F. Scott Fitzgerald",
      "nationality": "American",
      "birthdate": "1896-09-24"
    },
    {
      "name": "Another Author",
      "nationality": "Some other nationality",
      "birthdate": "Another birthdate"
    }
  ]
}
- 위와 같은 문서가 있는 경우,
- 특정 작가의 책을 찾기
- 국적별 작가의 책을 필터링 하기
- 작가의 속성을 기반으로 데이터를 집계하기 등에 사용 가능하다.

(Chat GPT)

**Comment by ShinyoungAshleyChoi** [comment]
> * 우리 회사에서도 Routing 값을 명시하여 검색을 수행하는 것은 어떠한가? 책에서는 운영 환경에서는 가능한 라우팅 값을 지정해 주는 것이 좋다고 하는데, 현재 우리 회사도 그렇게 수행되고 있는지?
- 라우팅을 이용하는 것은 성능 향상과 효율적인 샤드 운영에 도움이 될 수는 있으나 메모리 사용량이 늘어나고(라우팅 정보를 저장하는 메타데이터가 메모리에 저장됨) 유지보수(샤드 재할당 등)비용이 많이든다. 또한 라우팅을 지정하는 원칙과 방법이 또 하나의 관리 포인트가 될 수 있다. 라우팅 기능을 사용하면 좋은 사례는 부모 - 자식 관계를 가진 문서(게시글과 댓글)을 한 샤드에 넣는다면 이들을 같이 쿼리할 가능성이 크므로 성능 상의 이점을 누릴 수 있다. 이밖에 함꼐 쿼리될 가능성이 큰 문서들을 같은 라우팅으로 묶으면 좋다. 한편 데이터 분리와 보안으로서 라우팅을 사용할 수도 있는데 예를 들어 멀티 테넌시 애플레키에션에서 테넌트 별로 특정 데이터만 제공하고 싶은 경우 유용할 수 있다.
(Chat GPT & 내 생각~~~)

**Comment by hasuikhs** [comment]
> > * 성능에 문제가 있을 수 있는 nested Type을 굳이 사용하는 이유?
> 
> * 한 문서 내에서 1 대 다 관계가 있는 경우 사용할 수 있다.
> * {
>   "title": "The Great Gatsby",
>   "publication_year": 1925,
>   "authors": [
>   {
>   "name": "F. Scott Fitzgerald",
>   "nationality": "American",
>   "birthdate": "1896-09-24"
>   },
>   {
>   "name": "Another Author",
>   "nationality": "Some other nationality",
>   "birthdate": "Another birthdate"
>   }
>   ]
>   }
> * 위와 같은 문서가 있는 경우,
> * 특정 작가의 책을 찾기
> * 국적별 작가의 책을 필터링 하기
> * 작가의 속성을 기반으로 데이터를 집계하기 등에 사용 가능하다.
> 
> (Chat GPT)

위의 데이터를 object로 저장할 경우
"authors.name": [ "F. Scott Fitzgerald", "Another Author" ],
"authors.nationality": [ "American", "Some other nationality" ],
"authors.birthdate": [ "1896-09-24", "Another birthdate"  ]
로 평탄화 되어
"authors.name"이 "F. Scott Fitzgerald" and "authors.nationality"가 "Some other nationality" 인 옳지 않은 데이터를 가져올 수 있음

**Comment by ShinyoungAshleyChoi** [comment]
> > > * 성능에 문제가 있을 수 있는 nested Type을 굳이 사용하는 이유?
> > 
> > 
> > 
> > * 한 문서 내에서 1 대 다 관계가 있는 경우 사용할 수 있다.
> > * {
> >   "title": "The Great Gatsby",
> >   "publication_year": 1925,
> >   "authors": [
> >   {
> >   "name": "F. Scott Fitzgerald",
> >   "nationality": "American",
> >   "birthdate": "1896-09-24"
> >   },
> >   {
> >   "name": "Another Author",
> >   "nationality": "Some other nationality",
> >   "birthdate": "Another birthdate"
> >   }
> >   ]
> >   }
> > * 위와 같은 문서가 있는 경우,
> > * 특정 작가의 책을 찾기
> > * 국적별 작가의 책을 필터링 하기
> > * 작가의 속성을 기반으로 데이터를 집계하기 등에 사용 가능하다.
> > 
> > (Chat GPT)
> 
> 위의 데이터를 object로 저장할 경우 "authors.name": [ "F. Scott Fitzgerald", "Another Author" ], "authors.nationality": [ "American", "Some other nationality" ], "authors.birthdate": [ "1896-09-24", "Another birthdate" ] 로 평탄화 되어 "authors.name"이 "F. Scott Fitzgerald" and "authors.nationality"가 "Some other nationality" 인 옳지 않은 데이터를 가져올 수 있음

옳은 지적입니다! 다만 상술한 예시에서는 배제한 사례입니다.

**Comment by gwon7210** [comment]
1. 샤드의 생성 갯수의 기준은 무엇있나, 인덱스를 생성할 때 우리는 어떤 기준으로 샤드 개수를 추가하는지. (es node의 개수 = 샤드의 개수로 하면 되는가) 
2. primary shard 와 replication shard는 모두 검색은 가능하지만 색인의 역활은 primary shard만 담당하는가?
3. 우리는 number_of_replicas 갯수를 어떤 기준으로 설정하고 사용하는가
4. es 업그레이드를 점차적으로 할 경우, 서로 다른 es 버전이 클러스터로 사용할 수 있는가?

**Comment by ShinyoungAshleyChoi** [comment]
> 1. 샤드의 생성 갯수의 기준은 무엇있나, 인덱스를 생성할 때 우리는 어떤 기준으로 샤드 개수를 추가하는지. (es node의 개수 = 샤드의 개수로 하면 되는가)
- 샤드의 개수는 유즈 케이스마다 다르겠지만 공식문서에서는 1개의 샤드가 50GB를 넘지않도록  권장하고 있고 우리도 이를 고려하여 샤드를 배치하는 것으로 알고 있음
> 2. primary shard 와 replication shard는 모두 검색은 가능하지만 색인의 역활은 primary shard만 담당하는가?
- 프라이머리 샤드만 샤드에 참여한다. 레플리케이션 샤드는 색인을 마친 프라이머리 샤드의 복제본이다.

> 3. 우리는 number_of_replicas 갯수를 어떤 기준으로 설정하고 사용하는가
- 1개..ㅎ 레플리카를 늘리면 저장성능은 떨어지지만 읽기 성능이 좋아지고, 레플리카를 줄이면 저장성능은 좋아지지만 읽기 성능이 줄어듦, 우리는 문헌 용량이 워낙 대규모라 컴퓨팅 자원을 마음껏 쓰기에는 제약이 있어 1로 유지하는 것이 아닌가 싶습니다.

> 4. es 업그레이드를 점차적으로 할 경우, 서로 다른 es 버전이 클러스터로 사용할 수 있는가?
- 안 될 것 같습니다. (기능 충돌 등의 이유로)
